In [3]:
import pandas as pd
import plotly.express as px
import numpy as np
from constants import VERSION_ID
url = f'http://data.pmel.noaa.gov/socat/erddap/tabledap/{VERSION_ID}_decimated.csv?latitude,longitude,time,expocode,region_id,all_region_ids'

In [4]:
df = pd.read_csv(url, skiprows=[1])
df

,latitude,longitude,time,expocode,region_id,all_region_ids
0,49.827970,-2.815118,2018-08-14T18:55:03Z,069920180814,C,C
1,49.774110,-2.849303,2018-08-14T19:26:23Z,069920180814,C,C
2,49.644670,-2.963295,2018-08-14T20:33:03Z,069920180814,C,C
3,49.320490,-3.311380,2018-08-14T23:37:43Z,069920180814,C,C
4,49.156970,-3.461820,2018-08-15T00:44:43Z,069920180814,C,C
...,...,...,...,...,...,...
2337205,50.270000,-4.200012,2009-09-09T13:49:00Z,ZZ9920070416,C,C
2337206,50.320000,-4.170013,2009-09-09T14:09:00Z,ZZ9920070416,C,C
2337207,50.250000,-4.209991,2009-09-14T11:10:00Z,ZZ9920070416,C,C
2337208,50.330002,-4.170013,2009-09-14T11:50:00Z,ZZ9920070416,C,C
2337209,50.369999,-4.130005,2009-09-14T12:10:00Z,ZZ9920070416,C,C

In [5]:
import numpy as np
lat_bins = np.linspace(-90, 90, 80)
lon_bins = np.linspace(-180,180, 180)

In [6]:
df['lat_bin'] = pd.cut(df['latitude'], lat_bins)
df['lon_bin'] = pd.cut(df['longitude'], lon_bins)
df

,latitude,longitude,time,expocode,region_id,all_region_ids,lat_bin,lon_bin
0,49.827970,-2.815118,2018-08-14T18:55:03Z,069920180814,C,C,"(48.987, 51.266]","(-3.017, -1.006]"
1,49.774110,-2.849303,2018-08-14T19:26:23Z,069920180814,C,C,"(48.987, 51.266]","(-3.017, -1.006]"
2,49.644670,-2.963295,2018-08-14T20:33:03Z,069920180814,C,C,"(48.987, 51.266]","(-3.017, -1.006]"
3,49.320490,-3.311380,2018-08-14T23:37:43Z,069920180814,C,C,"(48.987, 51.266]","(-5.028, -3.017]"
4,49.156970,-3.461820,2018-08-15T00:44:43Z,069920180814,C,C,"(48.987, 51.266]","(-5.028, -3.017]"
...,...,...,...,...,...,...,...,...
2337205,50.270000,-4.200012,2009-09-09T13:49:00Z,ZZ9920070416,C,C,"(48.987, 51.266]","(-5.028, -3.017]"
2337206,50.320000,-4.170013,2009-09-09T14:09:00Z,ZZ9920070416,C,C,"(48.987, 51.266]","(-5.028, -3.017]"
2337207,50.250000,-4.209991,2009-09-14T11:10:00Z,ZZ9920070416,C,C,"(48.987, 51.266]","(-5.028, -3.017]"
2337208,50.330002,-4.170013,2009-09-14T11:50:00Z,ZZ9920070416,C,C,"(48.987, 51.266]","(-5.028, -3.017]"
2337209,50.369999,-4.130005,2009-09-14T12:10:00Z,ZZ9920070416,C,C,"(48.987, 51.266]","(-5.028, -3.017]"

In [7]:
pdf = df.groupby(['lat_bin', 'lon_bin', 'region_id'], as_index=False).count()
pdf

/tmp/ipykernel_1104/2723239263.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

,lat_bin,lon_bin,region_id,latitude,longitude,time,expocode,all_region_ids
0,"(-90.0, -87.722]","(-180.0, -177.989]",A,0,0,0,0,0
1,"(-90.0, -87.722]","(-180.0, -177.989]",C,0,0,0,0,0
2,"(-90.0, -87.722]","(-180.0, -177.989]",I,0,0,0,0,0
3,"(-90.0, -87.722]","(-180.0, -177.989]",N,0,0,0,0,0
4,"(-90.0, -87.722]","(-180.0, -177.989]",O,0,0,0,0,0
...,...,...,...,...,...,...,...,...
113123,"(87.722, 90.0]","(177.989, 180.0]",N,0,0,0,0,0
113124,"(87.722, 90.0]","(177.989, 180.0]",O,0,0,0,0,0
113125,"(87.722, 90.0]","(177.989, 180.0]",R,30,30,30,30,30
113126,"(87.722, 90.0]","(177.989, 180.0]",T,0,0,0,0,0
113127,"(87.722, 90.0]","(177.989, 180.0]",Z,0,0,0,0,0

In [8]:
pdf['lat_centers'] = pdf['lat_bin'].apply(lambda x: x.mid)
pdf['lon_centers'] = pdf['lon_bin'].apply(lambda x: x.mid)
pdf

,lat_bin,lon_bin,region_id,latitude,longitude,time,expocode,all_region_ids,lat_centers,lon_centers
0,"(-90.0, -87.722]","(-180.0, -177.989]",A,0,0,0,0,0,-88.861,-178.9945
1,"(-90.0, -87.722]","(-180.0, -177.989]",C,0,0,0,0,0,-88.861,-178.9945
2,"(-90.0, -87.722]","(-180.0, -177.989]",I,0,0,0,0,0,-88.861,-178.9945
3,"(-90.0, -87.722]","(-180.0, -177.989]",N,0,0,0,0,0,-88.861,-178.9945
4,"(-90.0, -87.722]","(-180.0, -177.989]",O,0,0,0,0,0,-88.861,-178.9945
...,...,...,...,...,...,...,...,...,...,...
113123,"(87.722, 90.0]","(177.989, 180.0]",N,0,0,0,0,0,88.861,178.9945
113124,"(87.722, 90.0]","(177.989, 180.0]",O,0,0,0,0,0,88.861,178.9945
113125,"(87.722, 90.0]","(177.989, 180.0]",R,30,30,30,30,30,88.861,178.9945
113126,"(87.722, 90.0]","(177.989, 180.0]",T,0,0,0,0,0,88.861,178.9945
113127,"(87.722, 90.0]","(177.989, 180.0]",Z,0,0,0,0,0,88.861,178.9945

In [9]:
pdf['lat_centers'] = pdf['lat_centers'].astype(float)
pdf['lon_centers'] = pdf['lon_centers'].astype(float)
pdf

,lat_bin,lon_bin,region_id,latitude,longitude,time,expocode,all_region_ids,lat_centers,lon_centers
0,"(-90.0, -87.722]","(-180.0, -177.989]",A,0,0,0,0,0,-88.861,-178.9945
1,"(-90.0, -87.722]","(-180.0, -177.989]",C,0,0,0,0,0,-88.861,-178.9945
2,"(-90.0, -87.722]","(-180.0, -177.989]",I,0,0,0,0,0,-88.861,-178.9945
3,"(-90.0, -87.722]","(-180.0, -177.989]",N,0,0,0,0,0,-88.861,-178.9945
4,"(-90.0, -87.722]","(-180.0, -177.989]",O,0,0,0,0,0,-88.861,-178.9945
...,...,...,...,...,...,...,...,...,...,...
113123,"(87.722, 90.0]","(177.989, 180.0]",N,0,0,0,0,0,88.861,178.9945
113124,"(87.722, 90.0]","(177.989, 180.0]",O,0,0,0,0,0,88.861,178.9945
113125,"(87.722, 90.0]","(177.989, 180.0]",R,30,30,30,30,30,88.861,178.9945
113126,"(87.722, 90.0]","(177.989, 180.0]",T,0,0,0,0,0,88.861,178.9945
113127,"(87.722, 90.0]","(177.989, 180.0]",Z,0,0,0,0,0,88.861,178.9945

In [10]:
pdf = pdf.loc[pdf['expocode'] > 0]
pdf

,lat_bin,lon_bin,region_id,latitude,longitude,time,expocode,all_region_ids,lat_centers,lon_centers
5788,"(-80.886, -78.608]","(-165.922, -163.911]",O,37,37,37,37,37,-79.7470,-164.9165
5796,"(-80.886, -78.608]","(-163.911, -161.899]",O,47,47,47,47,47,-79.7470,-162.9050
7164,"(-78.608, -76.329]","(-180.0, -177.989]",O,939,939,939,939,939,-77.4685,-178.9945
7172,"(-78.608, -76.329]","(-177.989, -175.978]",O,442,442,442,442,442,-77.4685,-176.9835
7180,"(-78.608, -76.329]","(-175.978, -173.966]",O,193,193,193,193,193,-77.4685,-174.9720
...,...,...,...,...,...,...,...,...,...,...
113093,"(87.722, 90.0]","(169.944, 171.955]",R,11,11,11,11,11,88.8610,170.9495
113101,"(87.722, 90.0]","(171.955, 173.966]",R,6,6,6,6,6,88.8610,172.9605
113109,"(87.722, 90.0]","(173.966, 175.978]",R,14,14,14,14,14,88.8610,174.9720
113117,"(87.722, 90.0]","(175.978, 177.989]",R,19,19,19,19,19,88.8610,176.9835
113125,"(87.722, 90.0]","(177.989, 180.0]",R,30,30,30,30,30,88.8610,178.9945

In [11]:
pdf['log'] = np.log10(pdf['expocode'])
pdf = pdf[['expocode','log','lat_centers', 'lon_centers', 'region_id']]
pdf = pdf.rename(columns={'expocode':'count', 'lat_centers':'latitude', 'lon_centers':'longitude'})
pdf

/tmp/ipykernel_1104/1391422971.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

        count       log  latitude  longitude region_id
5788       37  1.568202  -79.7470  -164.9165         O
5796       47  1.672098  -79.7470  -162.9050         O
7164      939  2.972666  -77.4685  -178.9945         O
7172      442  2.645422  -77.4685  -176.9835         O
7180      193  2.285557  -77.4685  -174.9720         O
...       ...       ...       ...        ...       ...
113093     11  1.041393   88.8610   170.9495         R
113101      6  0.778151   88.8610   172.9605         R
113109     14  1.146128   88.8610   174.9720         R
113117     19  1.278754   88.8610   176.9835         R
113125     30  1.477121   88.8610   178.9945         R

[9074 rows x 5 columns]

In [12]:
fig = px.scatter_geo(pdf, lat='latitude', lon='longitude', color='region_id',  hover_data=['latitude','longitude','count'],)
fig.update_layout(height=750)
fig.update_traces(marker={'size':7})
fig.show()

In [13]:
import os
from sqlalchemy import create_engine
connection_string = os.environ.get("DATABASE_URL", "postgresql://postgres:docker@127.0.0.1:5432")
engine = create_engine(connection_string)
pdf.to_sql("map_counts", con=engine, if_exists="replace", index=False)

74