In [4]:
from constants import redis_instance, FULL_CRUISE_DATA_FIELD_NAME, TIME_TO_LIVE, full_url, decimated_url, dtype_definitions
from sdig.erddap.info import Info
import pandas as pd
import json
from io import StringIO
import app

DEBUG:app:__app startup__ starting info query
DEBUG:app:__app startup__  finished info meta
DEBUG:app:__app startup__ finished info times

In [5]:
plot_in_expocode = '325019950721'
key = str(plot_in_expocode)

In [5]:

if redis_instance.hexists(key, FULL_CRUISE_DATA_FIELD_NAME):
    print('Reading cache')
    df_json_string = redis_instance.hget(str(plot_in_expocode), FULL_CRUISE_DATA_FIELD_NAME).decode('utf-8')
    df = pd.read_json(StringIO(json.loads(df_json_string)), dtype=dtype_definitions)
else:
    print('Filling cache')
    url = f'{full_url}.csv?{to_get}&expocode="{plot_in_expocode}"'            
    df = pd.read_csv(url, skiprows=[1], dtype=dtype_definitions)
    redis_instance.hset(key, FULL_CRUISE_DATA_FIELD_NAME, json.dumps(df.to_json()))
    # redis_instance.expire(key, TIME_TO_LIVE)
df

Reading cache

,expocode,dataset_name,platform_name,platform_type,organization,geospatial_lon_min,geospatial_lon_max,geospatial_lat_min,geospatial_lat_max,time_coverage_start,...,calc_speed,etopo2,gvCO2,dist_to_land,day_of_year,time,lon360,tmonth,nobs_full,nobs_deci
0,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,1.002844,3114.904474,360.132806,428.005692,202.529167,1995-07-21T12:42:00Z,65.8891,Jul,5055,5055
1,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,0.768960,3114.419444,360.132934,428.132697,202.532639,1995-07-21T12:47:00Z,65.8886,Jul,5055,5055
2,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,1.018234,3113.833758,360.133013,428.160489,202.535417,1995-07-21T12:51:00Z,65.8889,Jul,5055,5055
3,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,1.027035,3112.982421,360.133033,428.057644,202.538889,1995-07-21T12:56:00Z,65.8903,Jul,5055,5055
4,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,1.152000,3111.944345,360.133052,427.929948,202.543056,1995-07-21T13:02:00Z,65.8920,Jul,5055,5055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5050,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,4.174754,155.533954,357.778855,29.774921,227.854167,1995-08-15T20:30:00Z,58.9854,Aug,5055,5055
5051,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,5.027927,141.147709,357.778301,29.796760,227.857639,1995-08-15T20:35:00Z,58.9813,Aug,5055,5055
5052,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,4.327788,147.669272,357.777762,29.830433,227.860417,1995-08-15T20:39:00Z,58.9774,Aug,5055,5055
5053,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,3.745816,150.784191,357.777195,29.856593,227.863889,1995-08-15T20:44:00Z,58.9731,Aug,5055,5055
5054,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,3.745816,149.906259,357.776507,29.897642,227.868750,1995-08-15T20:51:00Z,58.9679,Aug,5055,5055

In [8]:
app.cache_data_for_key(key)
df = app.read_cache_for_key(key)
df

DEBUG:app:__cache_data_for_key__ caching data from: 325019950721
DEBUG:app:__cache_data_for_key__ Data for 325019950721 successfull cached.

,expocode,dataset_name,platform_name,platform_type,organization,geospatial_lon_min,geospatial_lon_max,geospatial_lat_min,geospatial_lat_max,time_coverage_start,...,calc_speed,etopo2,gvCO2,dist_to_land,day_of_year,time,lon360,tmonth,nobs_full,nobs_deci
0,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,1.002844,3114.904474,360.132806,428.005692,202.529167,1995-07-21T12:42:00Z,65.8891,Jul,5055,5055
1,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,0.768960,3114.419444,360.132934,428.132697,202.532639,1995-07-21T12:47:00Z,65.8886,Jul,5055,5055
2,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,1.018234,3113.833758,360.133013,428.160489,202.535417,1995-07-21T12:51:00Z,65.8889,Jul,5055,5055
3,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,1.027035,3112.982421,360.133033,428.057644,202.538889,1995-07-21T12:56:00Z,65.8903,Jul,5055,5055
4,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,1.152000,3111.944345,360.133052,427.929948,202.543056,1995-07-21T13:02:00Z,65.8920,Jul,5055,5055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5050,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,4.174754,155.533954,357.778855,29.774921,227.854167,1995-08-15T20:30:00Z,58.9854,Aug,5055,5055
5051,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,5.027927,141.147709,357.778301,29.796760,227.857639,1995-08-15T20:35:00Z,58.9813,Aug,5055,5055
5052,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,4.327788,147.669272,357.777762,29.830433,227.860417,1995-08-15T20:39:00Z,58.9774,Aug,5055,5055
5053,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,3.745816,150.784191,357.777195,29.856593,227.863889,1995-08-15T20:44:00Z,58.9731,Aug,5055,5055
5054,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,3.745816,149.906259,357.776507,29.897642,227.868750,1995-08-15T20:51:00Z,58.9679,Aug,5055,5055

In [7]:
df = app.read_cache_for_key(key)
tmin = '1995-08-07 19:46:15.1617'
from dateutil import parser
tmin_obj = parser.parse(tmin)
tmax = '1995-08-07 20:48:06.2706'
tmax_obj = parser.parse(tmax)
df = df[df['time'].between(tmin_obj.isoformat(), tmax_obj.isoformat(), inclusive='both')]
df

,expocode,dataset_name,platform_name,platform_type,organization,geospatial_lon_min,geospatial_lon_max,geospatial_lat_min,geospatial_lat_max,time_coverage_start,...,calc_speed,etopo2,gvCO2,dist_to_land,day_of_year,time,lon360,tmonth,nobs_full,nobs_deci
3400,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,2.678554,3053.120445,359.124030,325.979420,219.824306,1995-08-07T19:47:00Z,59.7731,Aug,5055,5055
3401,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,2.751115,3059.759487,359.124375,326.028295,219.827778,1995-08-07T19:52:00Z,59.7709,Aug,5055,5055
3402,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,0.173948,3067.781646,359.124697,326.032013,219.831250,1995-08-07T19:57:00Z,59.7683,Aug,5055,5055
3403,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,1.030883,3072.789923,359.124858,326.010868,219.861806,1995-08-07T20:41:00Z,59.7667,Aug,5055,5055
3404,325019950721,TT049,Thomas G. Thompson,Ship,Woods Hole Ocean Inst,57.311,68.7564,9.86899,23.3669,1995-07-21T00:00:00Z,...,0.519199,3077.245015,359.124893,325.924936,219.865278,1995-08-07T20:46:00Z,59.7653,Aug,5055,5055